// const { DataTypes } = require("sequelize");
// const sequelize = require("../config/db");

module.exports = (sequelize, DataTypes) => {
  const Question = sequelize.define(
    "Question",
    {
      id: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true,
      },
      questionText: {
        type: DataTypes.TEXT,
        allowNull: false,
      },
      // Choices
      optionA: { type: DataTypes.STRING, allowNull: false },
      optionB: { type: DataTypes.STRING, allowNull: false },
      optionC: { type: DataTypes.STRING, allowNull: false },
      optionD: { type: DataTypes.STRING, allowNull: false },

      // Logic & Metadata
      correctAnswer: {
        type: DataTypes.STRING,
        allowNull: false,
        validate: { isIn: [["A", "B", "C", "D"]] }, // Ensures data integrity
      },
      subject: {
        type: DataTypes.STRING,
        allowNull: false,
        defaultValue: "General",
      },

      // AI Metrics
      difficulty: {
        type: DataTypes.ENUM("Easy", "Medium", "Hard"),
        defaultValue: "Medium",
      },
      aiScore: {
        type: DataTypes.FLOAT,
        comment: "Linguistic complexity score generated by Natural.js",
      },
      reasoning: {
        type: DataTypes.TEXT,
        allowNull: true,
        comment: "AI justification for the assigned difficulty",
      },

      // Ownership: Tracks which Lecturer/Teacher created this
      teacherId: {
        type: DataTypes.INTEGER,
        allowNull: true, // Set to null if created by System Admin
      },
    },
    {
      // PROFESSIONAL OPTIMIZATION:
      // Indexes make the Adaptive Engine run significantly faster in MySQL
      indexes: [
        { fields: ["subject"] },
        { fields: ["difficulty"] },
        { fields: ["teacherId"] },
      ],
    },
  );

  /**
   * DATABASE RELATIONSHIPS:
   * Each question belongs to a teacher (Lecturer).
   */
  Question.associate = (models) => {
    Question.belongsTo(models.User, {
      foreignKey: "teacherId",
      as: "teacher",
      onDelete: "SET NULL", // If a teacher is deleted, keep the questions for the bank
    });
  };

  return Question;
};
